# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: Z:/CS-401-1-CompArch/Final_Project/MP_1_Compiler/Working_MP3/mips.srcs/sources_1/ip/dual_port_ram/dual_port_ram.xci
# IP: The module: 'dual_port_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/CS-401-1-CompArch/Final_Project/MP_1_Compiler/Working_MP3/mips.srcs/sources_1/ip/dual_port_ram/dual_port_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dual_port_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: Z:/CS-401-1-CompArch/Final_Project/MP_1_Compiler/Working_MP3/mips.srcs/sources_1/ip/dual_port_ram/dual_port_ram.xci
# IP: The module: 'dual_port_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/CS-401-1-CompArch/Final_Project/MP_1_Compiler/Working_MP3/mips.srcs/sources_1/ip/dual_port_ram/dual_port_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dual_port_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
